FROM nvcr.io/nvidia/pytorch:24.03-py3

RUN apt update && apt upgrade -y
RUN apt install -y htop
RUN apt install -y unzip
RUN apt install -y wget

RUN pip install protobuf==3.20.0
RUN pip install tensorboardX==1.6.0
RUN mkdir -p /opt/workspace

WORKDIR /opt/workspace/src
ADD benchmark_resnet.py /opt/workspace/src/benchmark_resnet.py
ADD benchmark_resnet_imagenet_localstorage.py /opt/workspace/src/benchmark_resnet_imagenet_localstorage.py
ADD benchmark_resnet_imagenet.py /opt/workspace/src/benchmark_resnet_imagenet.py
ADD mnist.py /opt/workspace/src/mnist.pytorch



RUN  chgrp -R 0 /opt/workspace \
  && chmod -R g+rwX /opt/workspace
